# Generated by Django 3.1.1 on 2020-10-16 07:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('HAMSTER', 'Hamster')], max_length=30)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=7)),
                ('race', models.IntegerField()),
                ('certificate', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('HAMSTER', 'Hamster')], max_length=20)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=7)),
                ('race', models.IntegerField()),
                ('age', models.IntegerField()),
                ('certificate', models.CharField(blank=True, max_length=30)),
                ('vaccines', models.CharField(max_length=30, validators=[django.core.validators.int_list_validator])),
                ('father', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='father', to='zoomate.parent', verbose_name="pet's father")),
            ],
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='animal', to='zoomate.animal', verbose_name="Animal in adoption")),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='zoomate.user', verbose_name="User giving adoption")),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='animal', to='zoomate.animal', verbose_name="Animal on sale")),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='zoomate.user', verbose_name="User doing sell")),
                ('price', models.Float()),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('icon', models.ImageField()),
            ],
        ),
        migrations.CreateModel(
            name='Races',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('category', models.ManyToOne(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='zoomate.categories', verbose_name='Category this race belongs to')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('category', models.ManyToOne(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='zoomate.categories', verbose_name='Category this vaccine belongs to')),
            ],
        ),
    ]
