# Generated by Django 3.1.3 on 2020-11-28 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoomate', '0002_auto_20201128_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='father',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='mother',
        ),
    ]
