# Generated by Django 3.1.3 on 2020-11-28 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoomate', '0003_auto_20201128_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='father',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_father', to='zoomate.animal'),
        ),
        migrations.AddField(
            model_name='animal',
            name='mother',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_mother', to='zoomate.animal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='upp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
